In [1]:
#Numpy
#Haute performance
#calculs robustes

import numpy as np

In [18]:
first = np.array([[1, 2, 3], [4, 5, 6]])

In [10]:
second = np.zeros((2, 3))

In [12]:
print(first.size)
print(second)

3
[[0. 0. 0.]
 [0. 0. 0.]]


In [39]:
def initialisation(m, n):
    matrix = np.random.randn(m, n)
    matrix = np.concatenate([matrix, np.ones((matrix.shape[0], 1))], 1)
    return matrix

initialisation(3, 4)

array([[ 1.11097654, -0.2886879 , -0.06974606, -1.04749667,  1.        ],
       [ 0.46450548, -0.73674588, -1.48106373, -0.26961562,  1.        ],
       [-0.77720836, -0.6318359 , -0.40662058,  0.62626424,  1.        ]])

In [19]:
first[0, 1]

2

In [33]:
first[0:2, 0:2]

array([[1, 2],
       [4, 5]])

In [34]:
B = np.zeros((4, 4))

In [35]:
B

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
B[1:3, 1:3] = 1

In [37]:
B

array([[0., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.]])

In [41]:
print(B.sum())

4.0


In [61]:
#Scipy 
#Calculs mathematiques scientifiques
import scipy as sc

#Scikit-Learn
#implementer des algorithmes de machine learning


#Pandas
#construite à partir de numpy
#calculs et visualisation 
import pandas as pd

#Matplotlib
#visualisation
import matplotlib as plt

In [56]:
x = np.linspace(0,2,100)
y = x**2

